### ISSUE TITLE
get_md5 not available

### ISSUE THREAD

**Issue by gk-fschubert** [geerlingguy/ansible-role-swap#32]
The latest pull request, added an issue. I can't find the parameter in the documentation. Or do only I have this problem?
https://docs.ansible.com/ansible/latest/collections/ansible/builtin/stat_module.html

TASK [swap : Check if swap file exists] ****************************************
fatal: [***********]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (stat) module: get_md5. Supported parameters include: checksum_algorithm, follow, get_attributes, get_checksum, get_mime, path (attr, attributes, checksum, checksum_algo, dest, mime, mime-type, mime_type, name)."}

**Comment by jcgruenhage** [comment]
`get_md5` was deprecated in https://github.com/ansible/ansible/commit/8386201242296e842b03f3e3826fcdbdf2dadfcb 6 years ago, and hidden from docs in https://github.com/ansible/ansible/commit/deae5b1bce9f434e67127ef0c8a46ed1d1f5544b 4 years ago.

The fix is using `get_checksum: false` instead of `get_md5: false`.

I ran into this in https://www.jeffgeerling.com/blog/2022/ansible-playbook-upgrade-ubuntudebian-servers-and-reboot-if-needed, and stumbled over this issue looking for the blog post source, but I guess that's not FOSS. @geerlingguy, could you fix it in the blog post?
