### ISSUE TITLE
Swap file is always recreated if the size is given as a number rather than a string

### ISSUE THREAD

**Issue by iay** [geerlingguy/ansible-role-swap#39]
This is probably obvious to people more used to reading Ansible examples, but the swap file size you provide to this role MUST be a string, e.g., "2048". If you set the parameter to a number, e.g., 2048, the file will always be removed and recreated.

It might be nice to have `argument_specs` so that this is detected.

**Comment by Floppy** [comment]
Note for others who may come across this issue; this just bit me even though I *thought* I was using a string. I set `swap_file_size_mb: "{{ ansible_memtotal_mb }}"`, thinking that because the quotes were there it would be a string. However, because of the quirk of ansible's variable interpolation in YAML, it put it through as a number. You need an explicit string conversion if you want to do this: `swap_file_size_mb: "{{ ansible_memtotal_mb | string }}"`

In terms of fixing this in the role, I think that the best defensive choice is probably to make sure both things are converted to the same type in the comparison at https://github.com/geerlingguy/ansible-role-swap/blob/f5f8343d7740899d7f7d71466ee638b9189688e4/tasks/main.yml#L15.
